Add final portfolio file
eyobyoseph/My-portfolio pull request #2
Opened 2022-12-03 22:29 UTC by eyobyoseph

2022-12-03 22:34 UTC, emmiiorji reviewed
Hi @eyobyoseph, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a pull request without a proper description. Kindly provide a description for your pull request. This will help to tell at a glance the changes accompanying your pull request.

![image](https://user-images.githubusercontent.com/20554583/205464864-e60c78c0-682f-4e7a-aa20-7ce2e917d31e.png)


Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-12-03 22:44 UTC, eyobyoseph commented
I thank you very much can you please tell me where can i write the description .here i have tried to describe my project
In this project I have added project and about me .
thanks in advance

2022-12-03 22:50 UTC, jerryowusu commented
> I thank you very much can you please tell me where can i write the description .here i have tried to describe my project In this project I have added project and about me . thanks in advance

Hello @eyobyoseph Kindly put your description at where it is written `no description` as shown in the image below

2022-12-03 22:53 UTC, jerryowusu reviewed
Hi @eyobyoseph , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

![invalid](https://user-images.githubusercontent.com/65233860/205465467-183aefbf-17a2-486c-bc4c-a9979fab32ba.png)


## Invalid Code Review Request

You have submitted a project that has no pull request  description/summary. Kindly put the descriptive summary in the place ilt is written `no description` as shown in the image below. 

![Screenshot from 2022-12-03 22-51-39](https://user-images.githubusercontent.com/65233860/205465461-7aff379e-fb9f-45b0-82cf-2803ef0d7b8a.png)


Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-12-05 13:58 UTC, franclobo requested changes
Hi @eyobyoseph, 

Good job so far!
You are doing it well 👏🏽 there are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights

- No linter errors ✔️ 
- Descriptive PR ✔️ 
- Correct Github flow ✔️ 
- Professional README file ✔️ 


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- **[OPTIONAL]** Kindly use an Images folder to contain all the images and organize your code.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-05 13:58 UTC, franclobo commented on index.html
> +      </section>
- [ ] **[OPTIONAL]** Your portfolio is the first impression for a recruiter, please correct this section, the background color, the font size, and color text to be similar to the Figma template 👇🏽 

| FIgma design | Your design |
|---|---|
| ![image](https://user-images.githubusercontent.com/58642949/205648507-37a3da57-3fac-48b1-986c-5265740c9106.png) | ![image](https://user-images.githubusercontent.com/58642949/205648624-89e51ac2-f92d-44d4-9e80-f25df11543aa.png) |

2022-12-05 13:58 UTC, franclobo commented on project.css
> +  padding: 0 24px 48px;
- [ ] Kindly correct the padding to look similar to the Figma template, we could use `padding: 0 0 48px;` 👍🏽

2022-12-05 13:58 UTC, franclobo commented on project.css
> +  height: 100vh;
- [ ] I suggest 🙏🏽 correcting the padding-top, the position of the button, and the height to be similar to the Figma template.

| Figma template | Your design |
|---|---|
| ![image](https://user-images.githubusercontent.com/58642949/205651783-21de74b2-72f0-41da-902d-1116b85a7bc6.png) | ![image](https://user-images.githubusercontent.com/58642949/205651695-11da90cb-7562-433d-a06c-a9a33ed5791a.png) |

2022-12-05 13:58 UTC, franclobo commented on project.css
> +  gap: 80px;
- [ ] I suggest 🙏🏽 deleting the gap to be similar to the Figma template.

2022-12-05 13:58 UTC, franclobo commented on index.html
> +            <h2  class="tonic4" >About Myself </h2>
- [ ] Kindly correct the title of the About section use "About Me" instead of "About Myself" to be similar to the Figma template.
- [ ] Please 🙏🏽 add the background image, use the correct font styles, and correct the paragraph position.

| Figma template | Your design |
|---|---|
| ![image](https://user-images.githubusercontent.com/58642949/205653143-4cd3cbcf-2c1a-4d2e-95c8-1a621f4c2438.png) | ![image](https://user-images.githubusercontent.com/58642949/205653059-4ff40b19-1095-478d-a5b9-863353efa780.png) |

2022-12-05 13:58 UTC, franclobo commented on index.html
> +        </div>
- [ ] Please use the correct font styles and correct the orthography to be similar to the Figma template 👇🏽 

| Figma template | Your design |
|---|---|
| ![image](https://user-images.githubusercontent.com/58642949/205653891-eb74bb8f-2957-49c1-8e6a-720a66563cd0.png) | ![image](https://user-images.githubusercontent.com/58642949/205653989-f159f25b-19aa-4ed9-83a2-23d59199ba35.png) |

2022-12-08 19:05 UTC, eyobyoseph commented on project.css
> +  padding: 0 24px 48px;
I have corrected the padding to look similar to Figma template
Thanks

2022-12-08 19:06 UTC, eyobyoseph commented on project.css
> +  height: 100vh;
I have corrected all of your comments
I thank you very much

2022-12-08 19:07 UTC, eyobyoseph commented on project.css
> +  gap: 80px;
I have deleted the gap to be similar to figma template

2022-12-08 19:09 UTC, eyobyoseph commented on index.html
> +        </div>
I have corrected according to your comment
Thanks

2022-12-08 19:23 UTC, algerina approved these changes
Hi @eyobyoseph , 
Good job so far! 

May I highlight the following:

- The repo looks professional.:heavy_check_mark:
- There are no linter errors:heavy_check_mark:
- You have descriptive PR:heavy_check_mark:
- Your project looks awesome:heavy_check_mark:

## STATUS: APPROVED :muscle::clap:

Congratulations! :tada:
Your project is complete!  It's time to merge it :shipit:
Great work on implementing the changes requested by the previous TSEs
 
<img src="https://media2.giphy.com/media/artj92V8o75VPL7AeQ/giphy.gif"/>

 ## Optional suggestions
 
 - Please check the comment under the review.

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._
Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

#### _**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**_
------------------------------------------------------------------------------------------------------------------------------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)
___
_If anything seems to be unclear to you, reach out and ask anything by commenting on this Pull Request and mention me as [Algerina](https://github.com/algerina), I will receive a notification and will respond._

[GitHub](https://github.com/algerina) | [LinkedIn](https://linkedin.com/in/amel-khiri) | [Twitter](https://twitter.com/AmelQahwadji)

_Reviewed by [Amel Khiri ](https://github.com/algerina)_

2022-12-08 19:23 UTC, algerina commented on about.css
> +  /* width: 327px; */
- [ Optional] Your current About me title is in 2 lines, please consider giving it a width as it was before (uncomment the line) and the problem will be fixed.

2022-12-08 20:02 UTC, merged